# Generated by Django 5.1.2 on 2024-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0002_portfolio_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv'),
        ),
    ]
