# Generated by Django 5.1.2 on 2024-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0003_alter_portfolio_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
