# Generated by Django 5.1.2 on 2024-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0004_alter_sociallink_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='self_image')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
