# Generated by Django 5.1.2 on 2024-10-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0005_selfimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfimage',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
