# Generated by Django 5.1.2 on 2024-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0008_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='App', max_length=100),
            preserve_default=False,
        ),
    ]
