# Generated by Django 5.1.2 on 2024-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0011_project_image_url_selfimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cv_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
