# Generated by Django 5.1.2 on 2024-10-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0012_portfolio_cv_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cv_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='selfimage',
            name='image_url',
        ),
    ]
